import os

from dotenv import load_dotenv

load_dotenv()

AWS_ACCESS_S3 = os.getenv("AWS_ACCESS_S3")
AWS_SECRET_S3 = os.getenv("AWS_SECRET_S3")
BUCKET_NAME = os.getenv("BUCKET_NAME")
REGION_NAME_S3 = os.getenv("REGION_NAME_S3")

AWS_ACCESS_REKOGNITION = os.getenv("AWS_ACCESS_REKOGNITION")
AWS_SECRET_REKOGNITION = os.getenv("AWS_SECRET_REKOGNITION")
REGION_NAME_REKOGNITION = os.getenv("REGION_NAME_REKOGNITION")

AWS_ACCESS_LEX = os.getenv("AWS_ACCESS_LEX")
AWS_SECRET_LEX = os.getenv("AWS_SECRET_LEX")
REGION_NAME_LEX = os.getenv("REGION_NAME_LEX")

AWS_ACCESS_TRANSLATE = os.getenv("AWS_ACCESS_TRANSLATE")
AWS_SECRET_TRANSLATE = os.getenv("AWS_SECRET_TRANSLATE")
REGION_NAME_TRANSLATE = os.getenv("REGION_NAME_TRANSLATE")